[build]
  command = "npm run build"
  publish = "dist"
  functions = "src/functions"

[dev]
  framework = "#custom"
  command = "webpack serve --mode development"
  port = 8888
  targetPort = 3000
  publish = "dist"
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18" 